import { useState } from 'react';
import type { DeviceConfig, DeviceStatus } from '../../../shared/schemas/models';
import { MatrixPreview } from '../components/MatrixPreview';
import { Button, SectionHeading, StatusBadge, Toggle } from '../components/Ui';

interface Props { status: DeviceStatus; config: DeviceConfig; onUpdate: (patch: Partial<DeviceConfig>) => Promise<void>; }

export function ClockPage({ status, config, onUpdate }: Props) {
  const [draft, setDraft] = useState(config.clock);
  const set = (patch: Partial<typeof draft>) => setDraft((current) => ({ ...current, ...patch }));
  return <div className="page-stack"><SectionHeading eyebrow="CLOCK SCREEN" title="Klok" description="Ontwerp de standaard klokweergave voor het 128×64 paneel." action={<StatusBadge tone="success">Europe / Amsterdam</StatusBadge>} /><div className="two-column-layout two-column-layout--clock"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">LAYOUT</span><h2>Weergave</h2></div></div><div className="layout-options">{(['minimal', 'classic', 'compact'] as const).map((layout) => <button key={layout} className={`layout-option ${draft.layout === layout ? 'is-selected' : ''}`} onClick={() => set({ layout })}><span className={`layout-option__icon layout-option__icon--${layout}`} /><span><strong>{layout[0].toUpperCase() + layout.slice(1)}</strong><small>{layout === 'minimal' ? 'Grote tijd, veel rust' : layout === 'classic' ? 'Tijd met scheidingslijn' : 'Compacte statusweergave'}</small></span>{draft.layout === layout && <b>✓</b>}</button>)}</div><div className="settings-list"><Toggle checked={draft.use24Hour} onChange={(use24Hour) => set({ use24Hour })} label="24-uurs notatie" /><Toggle checked={draft.showSeconds} onChange={(showSeconds) => set({ showSeconds })} label="Seconden tonen" /><Toggle checked={draft.showDate} onChange={(showDate) => set({ showDate })} label="Datum tonen" /><Toggle checked={draft.showStatusIndicator} onChange={(showStatusIndicator) => set({ showStatusIndicator })} label="Statusindicator" /></div><div className="color-fields"><label className="field"><span>Tijdkleur</span><input type="color" value={draft.timeColor} onChange={(event) => set({ timeColor: event.target.value })} /></label><label className="field"><span>Datumkleur</span><input type="color" value={draft.dateColor} onChange={(event) => set({ dateColor: event.target.value })} /></label><label className="field"><span>Lijnkleur</span><input type="color" value={draft.dividerColor} onChange={(event) => set({ dividerColor: event.target.value })} /></label><label className="field"><span>Achtergrond</span><input type="color" value={draft.backgroundColor} onChange={(event) => set({ backgroundColor: event.target.value })} /></label></div><div className="form-actions"><Button variant="primary" onClick={() => void onUpdate({ clock: draft })}>Klok opslaan</Button></div></section><section className="panel panel--preview"><div className="panel-heading"><div><span className="eyebrow">LIVE PREVIEW</span><h2>Interactieve klok</h2><p>De preview gebruikt dezelfde logische 128×64 coördinaten als de firmware.</p></div></div><MatrixPreview config={draft} status={status} /></section></div></div>;
}

