import { useState } from 'react';
import type { DeviceConfig, DeviceStatus } from '../../../shared/schemas/models';
import { MatrixPreview } from '../components/MatrixPreview';
import { Button, SectionHeading, StatusBadge, Toggle } from '../components/Ui';

interface Props { status: DeviceStatus; config: DeviceConfig; onUpdate: (patch: Partial<DeviceConfig>) => Promise<void>; }

export function DisplayPage({ status, config, onUpdate }: Props) {
  const [draft, setDraft] = useState(config.display);
  const set = (patch: Partial<typeof draft>) => setDraft((current) => ({ ...current, ...patch }));
  const save = () => void onUpdate({ display: draft });
  return <div className="page-stack"><SectionHeading eyebrow="DISPLAY CONTROL" title="Display" description="Regel de helderheid, voedingstoestand en automatische dimregeling." action={<StatusBadge tone={status.displayEnabled ? 'success' : 'warning'}>{status.displayEnabled ? 'Uitgang actief' : 'Uitgang uit'}</StatusBadge>} />
    <div className="two-column-layout"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">OUTPUT</span><h2>Basisinstellingen</h2></div><Toggle checked={draft.enabled} onChange={(enabled) => set({ enabled })} label="Aan" /></div><div className="form-grid"><label className="field field--wide"><span>Helderheid <strong>{draft.brightness}%</strong></span><input type="range" min="0" max={draft.maxBrightness} value={draft.brightness} onChange={(event) => set({ brightness: Number(event.target.value) })} /></label><label className="field"><span>Maximum brightness</span><div className="input-suffix"><input type="number" min="1" max="100" value={draft.maxBrightness} onChange={(event) => set({ maxBrightness: Number(event.target.value) })} /><b>%</b></div></label><label className="field field--check"><Toggle checked={draft.nightMode} onChange={(nightMode) => set({ nightMode })} /><span><strong>Nachtmodus</strong><small>Gebruik schema na zonsondergang</small></span></label><label className="field field--check"><Toggle checked={draft.scheduleEnabled} onChange={(scheduleEnabled) => set({ scheduleEnabled })} /><span><strong>Automatisch schema</strong><small>Dim helderheid op vaste tijden</small></span></label></div><div className="form-actions"><Button variant="primary" onClick={save}>Wijzigingen opslaan</Button></div></section><section className="panel panel--preview"><div className="panel-heading"><div><span className="eyebrow">PIXEL PREVIEW</span><h2>Brightness simulatie</h2></div></div><MatrixPreview config={{ ...config.clock, backgroundColor: '#050915' }} status={{ ...status, brightness: Math.min(draft.brightness, draft.maxBrightness), displayEnabled: draft.enabled }} /></section></div>
    <section className="panel"><div className="panel-heading"><div><span className="eyebrow">SCHEDULE</span><h2>Helderheidsschema</h2><p>Standaardprofiel voor een rustig indoor display.</p></div><Button onClick={() => set({ brightnessSchedule: [...draft.brightnessSchedule, { id: `custom-${Date.now()}`, time: '12:00', brightness: 20 }] })}>+ Tijd toevoegen</Button></div><div className="schedule-table"><div className="schedule-row schedule-row--head"><span>Tijd</span><span>Helderheid</span><span /><span /></div>{draft.brightnessSchedule.map((entry, index) => <div className="schedule-row" key={entry.id}><input type="time" value={entry.time} onChange={(event) => set({ brightnessSchedule: draft.brightnessSchedule.map((item, i) => i === index ? { ...item, time: event.target.value } : item) })} /><label className="schedule-slider"><input type="range" min="0" max={draft.maxBrightness} value={entry.brightness} onChange={(event) => set({ brightnessSchedule: draft.brightnessSchedule.map((item, i) => i === index ? { ...item, brightness: Number(event.target.value) } : item) })} /><span>{entry.brightness}%</span></label><span className="schedule-preview-dot" style={{ opacity: Math.max(0.16, entry.brightness / 100) }} /><button className="icon-button" aria-label="Verwijder tijd" onClick={() => set({ brightnessSchedule: draft.brightnessSchedule.filter((item) => item.id !== entry.id) })}>×</button></div>)}</div><div className="form-actions"><Button variant="primary" onClick={save}>Schema opslaan</Button></div></section>
  </div>;
}

