import { useEffect, useMemo, useRef, useState } from 'react';
import type { DeviceConfig, DeviceStatus, LayoutModel } from '../../../shared/schemas/models';
import type { DeviceApi } from '../api/deviceApi';
import { MatrixPreview } from '../components/MatrixPreview';
import { Button, EmptyState, SectionHeading, StatusBadge } from '../components/Ui';

interface Props { api: DeviceApi; status: DeviceStatus; config: DeviceConfig; onUpdate: (patch: Partial<DeviceConfig>) => Promise<void>; onNotify: (message: string, kind?: 'success' | 'error' | 'info') => void; }

export function LayoutsPage({ api, status, config, onUpdate, onNotify }: Props) {
  const [layouts, setLayouts] = useState<LayoutModel[]>(config.layouts ?? []);
  const [selectedId, setSelectedId] = useState(config.activeLayoutId ?? layouts[0]?.id);
  const [category, setCategory] = useState('all');
  const fileRef = useRef<HTMLInputElement>(null);
  useEffect(() => { void api.getLayouts().then(setLayouts).catch(() => setLayouts(config.layouts ?? [])); }, [api, config.layouts]);
  const selected = layouts.find((layout) => layout.id === selectedId) ?? layouts[0];
  const filtered = useMemo(() => category === 'all' ? layouts : layouts.filter((layout) => layout.category === category), [category, layouts]);
  const activate = async (layout: LayoutModel) => { setSelectedId(layout.id); await onUpdate({ activeLayoutId: layout.id }); onNotify(`Layout actief: ${layout.name}`); };
  const duplicate = async () => { if (!selected) return; const copy: LayoutModel = { ...structuredClone(selected), id: `${selected.id}-copy-${Date.now()}`, name: `${selected.name} kopie`, metadata: { ...selected.metadata, updatedAt: new Date().toISOString() } }; await api.saveLayout(copy); setLayouts((items) => [...items, copy]); setSelectedId(copy.id); onNotify('Layout gedupliceerd'); };
  const remove = async () => { if (!selected || selected.id === config.activeLayoutId || selected.id === 'clock-main') { onNotify('Actieve of hoofd-layout kan niet worden verwijderd', 'error'); return; } await api.deleteLayout(selected.id); setLayouts((items) => items.filter((item) => item.id !== selected.id)); setSelectedId(layouts[0]?.id); onNotify('Layout verwijderd'); };
  const exportLayout = () => { if (!selected) return; const blob = new Blob([JSON.stringify(selected, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `${selected.id}.json`; anchor.click(); URL.revokeObjectURL(url); };
  const importLayout = async (file: File) => { try { const imported = JSON.parse(await file.text()) as LayoutModel; if (imported.width !== 128 || imported.height !== 64 || !imported.id || !Array.isArray(imported.elements)) throw new Error('Ongeldig 128x64 layoutbestand'); await api.saveLayout(imported); setLayouts((items) => [...items.filter((item) => item.id !== imported.id), imported]); setSelectedId(imported.id); onNotify('Layout geïmporteerd'); } catch (error) { onNotify(error instanceof Error ? error.message : 'Import mislukt', 'error'); } };
  return <div className="page-stack"><SectionHeading eyebrow="LAYOUT LIBRARY" title="Layouts" description="Beheer de versioned 128×64 layouts die door portal, mock device en later firmware worden gebruikt." action={<StatusBadge tone="success">{layouts.length} layouts</StatusBadge>} /><div className="two-column-layout"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">LIBRARY</span><h2>Beschikbare layouts</h2></div><select value={category} onChange={(event) => setCategory(event.target.value)}><option value="all">Alle categorieën</option><option value="clock">Klok</option><option value="generic_message">Bericht</option><option value="home_assistant">Home Assistant</option><option value="p2000">P2000</option><option value="alert">Alert</option><option value="timer">Timer</option></select></div>{filtered.length ? <div className="endpoint-list">{filtered.map((layout) => <div key={layout.id} className={selected?.id === layout.id ? 'is-selected' : ''}><button className="text-button" onClick={() => setSelectedId(layout.id)}><strong>{layout.name}</strong><span>{layout.category} · {layout.elements.length} elementen</span></button>{config.activeLayoutId === layout.id && <StatusBadge tone="success">Actief</StatusBadge>}</div>)}</div> : <EmptyState icon="▦" title="Geen layouts" description="Importeer een layout of reset de mock simulator." />}<div className="form-actions"><Button onClick={() => fileRef.current?.click()}>Import JSON</Button><input ref={fileRef} hidden type="file" accept="application/json" onChange={(event) => { const file = event.target.files?.[0]; if (file) void importLayout(file); event.target.value = ''; }} /><Button onClick={exportLayout}>Export JSON</Button><Button onClick={() => void duplicate()} disabled={!selected}>Dupliceren</Button><Button variant="danger" onClick={() => void remove()} disabled={!selected}>Verwijderen</Button></div></section><section className="panel panel--preview"><div className="panel-heading"><div><span className="eyebrow">LAYOUT PREVIEW</span><h2>{selected?.name ?? 'Geen selectie'}</h2><p>{selected?.metadata?.description ?? 'Selecteer een layout uit de library.'}</p></div>{selected && <Button variant="primary" onClick={() => void activate(selected)}>Als idle instellen</Button>}</div>{selected ? <MatrixPreview config={config.clock} status={{ ...status, mode: selected.category === 'clock' ? 'CLOCK' : 'MESSAGE', activeLayout: selected.id }} layout={selected} /> : <EmptyState icon="▦" title="Geen layout geselecteerd" description="Selecteer een layout om de preview te openen." />}</section></div></div>;
}
