[platformio]
boards_dir = boards
default_envs = waveshare-esp32-s3-rgb-matrix

[env:waveshare-esp32-s3-rgb-matrix]
platform = espressif32
board = waveshare_esp32_s3_rgb_matrix
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.filesystem = littlefs
board_build.partitions = huge_app.csv
lib_ldf_mode = chain+
build_flags =
  -DSMART_MATRIX_HARDWARE_TEST=1
  -DCORE_DEBUG_LEVEL=1
lib_deps =
  https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA.git
  https://github.com/ESP32Async/ESPAsyncWebServer.git
  https://github.com/ESP32Async/AsyncTCP.git
  adafruit/Adafruit GFX Library@^1.11.11
  bblanchon/ArduinoJson@^7.0.4
